language: node_js
node_js:
  - 7
  - 6
before_script:
  - npm install -g yeoman
  - npm install
  - npm link
before_deploy:
  - npm install -g nsp
  - npm install
script:
  - 'mkdir $HOME/humpbacktest && cd $HOME/humpbacktest'
  - 'yo humpback --humanName="humpbacktest" --appName="humpbacktest" --skip-install'
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
