language: node_js
node_js:
  - 12
  - 10
  - 8
before_install:
  - npm install -g npm@latest
before_script:
  - npm install -g yo
  - npm install
  - npm link
  - curl https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.2933/circleci-cli_0.1.2933_linux_amd64.tar.gz -LO
  - tar xvf circleci-cli_0.1.2933_linux_amd64.tar.gz
  - mv circleci-cli_0.1.2933_linux_amd64/circleci $HOME/circleci
  - chmod +x $HOME/circleci
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - npm install
script:
  - 'mkdir $HOME/humpbacktest && cd $HOME/humpbacktest'
  - 'yo humpback --humanName="humpbacktest" --appName="humpbacktest" --deployEnv="Pantheon"'
  - npm audit | grep -E "(High | Critical)" -B3 -A10 ; CODE=$? ; if [ $CODE -eq 0 ] ; then echo "Vulnerabilities found" ; exit 1; fi
  - $HOME/circleci config validate
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
