language: node_js
node_js:
  - 8
  - 7
  - 6
before_script:
  - npm install -g yo
  - npm install
  - npm link
  - curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh --fail --show-error | bash
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - npm install -g nsp
  - npm install
script:
  - 'mkdir $HOME/humpbacktest && cd $HOME/humpbacktest'
  - 'yo humpback --humanName="humpbacktest" --appName="humpbacktest" --skip-install'
  - circleci config validate
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
